models/Book.php
<?php

namespace app\models;

use Yii;

class Book extends \yii\db\ActiveRecord {
	
	private $name;
	
	static public function tableName() {
		return 'books';
	}
	/*public function rules() {
		return [
			[['idbook'], 'integer'],
			[['idbook'],'required'],
			[['idauthor'],'integer'],
			[['idauthor'],'required'],
		];
	}*/
}
?>

models/RubricsRecord.php
<?php

namespace app\models;
use Yii;

/**
 * This is the model class for table "rubrics".
 *
 * @property integer $id
 * @property string $name
 *
 * @property Bookrubrics[] $bookrubrics
 * @property Books[] $idbooks
 */
class RubricsRecord extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rubrics';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Рубрика',
        ];
    }
    
    
    public function getNames() {
       return $this->find()->indexBy('id')->all();
    }
    
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBookrubrics()
    {
        return $this->hasMany(Bookrubrics::className(), ['idrubric' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdbooks()
    {
        return $this->hasMany(BooksRecord::className(), ['id' => 'idbook'])->viaTable('bookrubrics', ['idrubric' => 'id']);
    }
}

controllers/AuthorsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\AuthorsRecord;
use app\models\AuthorsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\ForbiddenHttpException;
/**
 * AuthorsController implements the CRUD actions for AuthorsRecord model.
 */
class AuthorsController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all AuthorsRecord models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AuthorsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single AuthorsRecord model.
     * @param integer $id
     * @param string $name
     * @param string $surname
     * @return mixed
     */
    public function actionView($id, $name, $surname)
    {
        return $this->render('view', [
            'model' => $this->findModel($id, $name, $surname),
        ]);
    }

    /**
     * Creates a new AuthorsRecord model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if(Yii::$app->user->isGuest) throw new ForbiddenHttpException('Вы не зарегистрированный пользователь. Пожалуйста, авторизируйтесь.');
        $model = new AuthorsRecord();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->goBack();
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    
    public function storeReturnUrl() {
        Yii::$app->user->returnUrl = Yii::$app->request->url;
    }
    
    public function actionBooks($id) {
        $model  = AuthorsRecord::findOne($id);
        $model = $model->idbooks;
        $dataProvider = new \yii\data\ArrayDataProvider(
          [ 'allModels' => $model,
            'pagination' => false
          ]
        );

       return $this->render('authorbooks', [
            'dataProvider' => $dataProvider
        ]);
    }
    
    
    /**
     * Updates an existing AuthorsRecord model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @param string $name
     * @param string $surname
     * @return mixed
     */
    public function actionUpdate($id, $name, $surname)
    {
        if(Yii::$app->user->isGuest) throw new ForbiddenHttpException('Вы не зарегистрированный пользователь. Пожалуйста, авторизируйтесь.');
        $model = $this->findModel($id, $name, $surname);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id, 'name' => $model->name, 'surname' => $model->surname]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing AuthorsRecord model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @param string $name
     * @param string $surname
     * @return mixed
     */
    public function actionDelete($id, $name, $surname)
    {
        if(Yii::$app->user->isGuest) throw new ForbiddenHttpException('Вы не зарегистрированный пользователь. Пожалуйста, авторизируйтесь.');
        $this->findModel($id, $name, $surname)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the AuthorsRecord model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @param string $name
     * @param string $surname
     * @return AuthorsRecord the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, $name, $surname)
    {
        if (($model = AuthorsRecord::findOne(['id' => $id, 'name' => $name, 'surname' => $surname])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Запрашиваемая страница не найдена');
        }
    }
}

controllers/BooksController.php
<?php

namespace app\controllers;

use Yii;

use app\models\BooksRecord;
use app\models\AuthorsRecord;
use app\models\BookRubricRecord;
use app\models\BookAuthorRecord;
use app\models\BooksSearch;
use app\models\Author;
use app\models\Rubric;

use yii\web\ForbiddenHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * BooksController implements the CRUD actions for BooksRecord model.
 */
class BooksController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all BooksRecord models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BooksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single BooksRecord model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new BooksRecord model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if(Yii::$app->user->isGuest) throw new ForbiddenHttpException('Вы не зарегистрированный пользователь. Пожалуйста, авторизируйтесь.');
        
        $this->storeReturnUrl();
     
        $model = new BooksRecord;
        $author = new Author;
        $rubric = new Rubric;
        
        if (Yii::$app->request->isPost && 
            $model->tryLoad(Yii::$app->request->post(), UploadedFile::getInstance($model, 'foto')) && 
            $author->load(Yii::$app->request->post()) && 
            $rubric->load(Yii::$app->request->post()) && 
            $model->save()) {
              foreach($author->idauthors as $idauthor) {
                    $bookauth = new BookAuthorRecord();
                    $bookauth->idbook = $model->id;
                    $bookauth->idauthor = $idauthor;
                    $bookauth->save(); 
                }
                
              foreach($rubric->idrubrics as $idrubric) {
                    $bookrubr = new BookRubricRecord();
                    $bookrubr->idbook = $model->id;
                    $bookrubr->idrubric = $idrubric;
                    $bookrubr->save(); 
                }
                
            return $this->redirect(['view', 'id' => $model->id]);
         
         }
         else {
            return $this->render('create', compact('model', 'author', 'rubric'));//['model' => $model]);
        }
    }
    
    public function storeReturnUrl() {
        Yii::$app->user->returnUrl = Yii::$app->request->url;
    }
    
    /**
     * Updates an existing BooksRecord model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        
        if(Yii::$app->user->isGuest) throw new ForbiddenHttpException('Вы не зарегистрированный пользователь. Пожалуйста, авторизируйтесь.');
     
        $this->storeReturnUrl();
        $model = $this->findModel($id);
        $author = new Author;
        $rubric = new Rubric;
        
        /*if ($model->load(Yii::$app->request->post()) && $model->upload(UploadedFile::getInstance($model, 'foto')) && $model->save()) {*/
        if(Yii::$app->request->isPost && 
            $model->tryLoad(Yii::$app->request->post(), UploadedFile::getInstance($model, 'foto')) && 
            $author->load(Yii::$app->request->post()) && 
            $rubric->load(Yii::$app->request->post()) && 
            $model->save()) {
                
            BookAuthorRecord::deleteAll("idbook = {$model->id}");
              foreach($author->idauthors as $idauthor) {
                    $bookauth = new BookAuthorRecord();
                    $bookauth->idbook = $model->id;
                    $bookauth->idauthor = $idauthor;
                    $bookauth->save();
                }
                
            BookRubricRecord::deleteAll("idbook = {$model->id}");
              foreach($rubric->idrubrics as $idrubric) {
                    $bookrubr = new BookRubricRecord();
                    $bookrubr->idbook = $model->id;
                    $bookrubr->idrubric = $idrubric;
                    $bookrubr->save(); 
                }
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', compact('model', 'author', 'rubric'));//['model' => $model]);
            /*return $this->render('update', [
                'model' => $model,
            ]);*/
        }
    }

    /**
     * Deletes an existing BooksRecord model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
     
        if(Yii::$app->user->isGuest) throw new ForbiddenHttpException('Вы не зарегистрированный пользователь. Пожалуйста, авторизируйтесь.');
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the BooksRecord model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return BooksRecord the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = BooksRecord::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Запрашиваемая страница не найдена.');
        }
    }
}

controllers/RubricsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\RubricsRecord;
use app\models\RubricsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\web\ForbiddenHttpException;
/**
 * RubricsController implements the CRUD actions for RubricsRecord model.
 */
class RubricsController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all RubricsRecord models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RubricsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single RubricsRecord model.
     * @param integer $id
     * @param string $name
     * @return mixed
     */
    public function actionView($id, $name)
    {
        return $this->render('view', [
            'model' => $this->findModel($id, $name),
        ]);
    }

    /**
     * Creates a new RubricsRecord model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if(Yii::$app->user->isGuest) throw new ForbiddenHttpException('Вы не зарегистрированный пользователь. Пожалуйста, авторизируйтесь.');
        $model = new RubricsRecord();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->goBack();
      
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    
    
     public function actionBooks($id) {
        $model  = RubricsRecord::findOne($id);
        $model = $model->idbooks;
        $dataProvider = new \yii\data\ArrayDataProvider(
          [ 'allModels' => $model,
            'pagination' => false
          ]
        );

       return $this->render('rubricbooks', [
            'dataProvider' => $dataProvider
        ]);
        }
        
        
    /**
     * Updates an existing RubricsRecord model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @param string $name
     * @return mixed
     */
    public function actionUpdate($id, $name)
    {
     
        if(Yii::$app->user->isGuest) throw new ForbiddenHttpException('Вы не зарегистрированный пользователь. Пожалуйста, авторизируйтесь.');
        $model = $this->findModel($id, $name);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id, 'name' => $model->name]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing RubricsRecord model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @param string $name
     * @return mixed
     */
    public function actionDelete($id, $name)
    {
        if(Yii::$app->user->isGuest) throw new ForbiddenHttpException('Вы не зарегистрированный пользователь. Пожалуйста, авторизируйтесь.');
        $this->findModel($id, $name)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the RubricsRecord model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @param string $name
     * @return RubricsRecord the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, $name)
    {
        if (($model = RubricsRecord::findOne(['id' => $id, 'name' => $name])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Данная страница не найдена');
            return $model;
        }
    }
}

views/books/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\ActiveField;
use app\models\AuthorsRecord;
use app\models\RubricsRecord;
use app\models\Author;
use yii\helpers\ArrayHelper;


/* @var $this yii\web\View */
/* @var $model app\models\BooksRecord */
/* @var $form yii\widgets\ActiveForm */


?>
<div class="books-record-form">

    <?php $form = ActiveForm::begin([
                                'id' => 'create-book-form',
                                'options' => ['enctype' => 'multipart/form-data'],
                                ]);
        
        $authors = new AuthorsRecord;
        $rubrics = new RubricsRecord;
    ?>
    
    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'foto')->fileInput(['accept' => 'image/*']) ?>
    
    <?= $form->field($author, 'idauthors')->listBox(ArrayHelper::map($authors->allFullNames, 'id', 'fullname'), ['multiple' => true]) ?>
    <?= Html::a('<span class="glyphicon glyphicon-plus"></span>&nbsp&nbspДобавить автора.',['authors/create'])?>
    
    <?= $form->field($rubric, 'idrubrics')->listBox(ArrayHelper::map($rubrics->names, 'id', 'name'), ['multiple' => true]) ?>
    <?= Html::a('<span class="glyphicon glyphicon-plus"></span>&nbsp&nbspДобавить рубрику.',['rubrics/create'])?>
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/books/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BooksSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="books-record-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'foto') ?>

    <div class="form-group">
        <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Отмена', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/books/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BooksRecord */

$this->title = 'Добавить книгу';
$this->params['breadcrumbs'][] = ['label' => 'Запись о книгах', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="books-record-create">

    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', [
        'model' => $model,
        'author' => $author,
        'rubric' => $rubric
    ]) ?>
</div>

views/books/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
//use app\models\BooksRecord;

/* @var $this yii\web\View */
/* @var $searchModel app\models\BooksSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Записи по книгам';
$this->params['breadcrumbs'][] = $this->title;
app\assets\ApplicationAsset::register($this);
?>
<div class="books-record-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php  //echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
         <?php if(!Yii::$app->user->isGuest): ?>
        <?= Html::a('Добавить новую книгу', ['create'], ['class' => 'btn btn-success']) ?>
        <?php endif?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'name',
            'foto:image',
            [
                'label' => 'Автор(ы)',
                'format' => 'paragraphs',
                'value' => function($model) {
                    $return = $model->idauthors;
                    $result = '';   
                    foreach($return as $author) {
                        $result .= implode(' ',array_filter($author->getAttributes(['name','surname']))). "\n\n";
                    }
                return $result;
                }
            ],
            [
                'label' => 'Рубрика(и)',
                'format' => 'paragraphs',
                'value' => function($model) {
                    $return = $model->idrubrics;
                    $result = '';
                    foreach($return as $rubric) {
                        $result .= implode(' ',$rubric->getAttributes(['name']))."\n\n";
                    }
                return $result;
                },
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'visible' => !Yii::$app->user->isGuest
            ],
        ],
    ]); ?>

</div>

views/books/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\BooksRecord */

$this->title = 'Обновление записи о книге: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Записи о книгах', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="books-record-update">

    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', [
        'model' => $model,
        'author' => $author,
        'rubric' => $rubric
    ]) ?>

</div>

views/books/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\BooksRecord */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Книги', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="books-record-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php if(!Yii::$app->user->isGuest): ?>
        <?= Html::a('Обновить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены что хотите удалить данную запись ?',
                'method' => 'post',
            ],
        ]) ?>
        <?php endif?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            'foto:image',
        ],
    ]) ?>

</div>